In [4]:
# Arrays
import numpy as np

def arrays(arr):
    # complete this function
    # use numpy.array
    return(np.array(arr[::-1],float))
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [9]:
# Shape and Reshape
import numpy as np
n=list(map(int,input().split()))
a=np.array(n)
a.shape=(3,3)
print(a)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
# transpose and flatten
import numpy
n,m = list(map(int, input().split()))
a =[input().split() for i in range(n)]
arr=np.array(a,int)
print(arr.transpose())
print(arr.flatten())


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [6]:
# transpose and flatten
import numpy
n,m = list(map(int, input().split()))
a =[input().split() for i in range(n)]
arr=numpy.array(a,int)
print(numpy.array(a,int).transpose())
print(numpy.array(a,int).flatten())


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [33]:
# Zeros and Ones
import numpy
n=tuple(map(int,input().split()))
print(numpy.zeros(n))
print(numpy.ones(n))


3 3 3
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [5]:
# Eye and Identity
a,b = map(int,input().split())
print(np.eye(n, m))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [9]:
# Array mathematics
n,m = map(int,input().split())
a = np.array([input().split() for i in range(n)],dtype=int)
b = np.array([input().split() for i in range(n)],dtype=int)
print(a + b)
print(a - b)
print(a * b)
print(a // b)
print(a % b)
print(a ** b)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [10]:
# Floor,ceil and rint
n=np.array(input().split(),dtype=float)
print(np.floor(n))
print(np.ceil(n))
print(np.rint(n))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [11]:
# Sum and Product
n,m = map(int,input().split())
a = np.array([input().split()for i in range(n)],dtype=int)
sums = np.sum(a,axis=0)
product=np.product(sums)
print(product)

2 2
1 2
3 4
24


In [1]:
# Min and Max
import numpy as np
n,m = map(int,input().split())
a = np.array([input().split()for i in range(n)],dtype=int)
min=np.min(a,axis=1)
print(max(min))

4 2
2 5
3 7
1 3
4 0
3


In [2]:
# Mean,var and Std
n,m = map(int,input().split())
a = np.array([input().split()for i in range(n)],dtype=int)
print(np.mean(a,axis=1))
print(np.var(a,axis=0))
print(np.std(a))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


In [3]:
# Dot and Cross
n = int(input())
a = np.array([input().split()for i in range(n)],dtype=int)
b = np.array([input().split()for i in range(n)],dtype=int)
print(a.dot(b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [5]:
# Inner and Outer
a, b = (np.array(list(input().split()), dtype=int) for _ in range(2))
print(np.inner(a,b))
print(np.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]


In [6]:
# Polynomials
a = np.array(input().split(),dtype=float)
print(np.polyval(a,int(input())))

1.1 2 3
0
3.0


In [8]:
# Linear algebra
n=int(input())
a = np.array([input().split()for i in range(n)],dtype=float)
print(np.linalg.det(a))

2
1.1 1.1
1.1 1.1
0.0
